CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE verification (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), 
  identifier TEXT NOT NULL, 
  value TEXT NOT NULL, 
  expires_at TIMESTAMPTZ NOT NULL, 
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL, 
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);
